UPDATE
    `session`
SET
    `sessionCode`=:sessionCode,
    `sessionFingerprint`=:sessionFingerprint,
    `sessionCreated`=:sessionCreated,
    `sessionActivity`=:sessionActivity,
    `sessionData`=:sessionData
WHERE
    `sessionCode`=:sessionCode